config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' },
  path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  as :user do
    get 'login', to: 'devise/sessions#new'
  end

  resources :groups do
    post 'join', to: 'memberships#create'
    delete 'leave', to: 'memberships#destroy'

    get 'members', to: 'members#index'

    resources :events do
      resources 'organizers', only: [:create, :destroy]

      post 'rsvp', to: 'rsvps#create'
    end
  end

  authenticated :user do
    root 'dashboard#index', as: :authenticated_root
  end

  root 'landing#index'
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  def index
    @groups_as_admin = current_user.groups_as_admin
    @groups_as_normal = current_user.groups_as_normal
  end
end

app/views/dashboard/index.html.erb
<div>
  <%= link_to_delete 'Logout', destroy_user_session_path, :user %>

  <h1> Hello <%= current_user.name %></h1>

  <ul>
    <% @groups_as_admin.each do |group| %>
      <li>
        <h2> <%= link_to group.name, group %> </h2>
        <p> Description: <%= group.description %> </p>
        <p> Region: <%= group.region %> </p>
      </li>
    <% end %>
  </ul>

  <ul>
    <% @groups_as_normal.each do |group| %>
      <li>
        <h2> <%= link_to group.name, group %> </h2>
        <p> Description: <%= group.description %> </p>
        <p> Region: <%= group.region %> </p>
      </li>
    <% end %>
  </ul>

  <%= link_to 'Create group', new_group_path %>

  <%= link_to 'Check the groups around', groups_path %>
</div>