config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' },
  path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  as :user do
    get 'login', to: 'devise/sessions#new'
  end

  resources :groups do
    post 'join', to: 'memberships#create'
    delete 'leave', to: 'memberships#destroy'

    get 'members', to: 'members#index'

    resources :events do
      resources 'organizers', only: [:create, :destroy]

      post 'rsvp', to: 'rsvps#create'
    end
  end

  authenticated :user do
    root 'dashboard#index', as: :authenticated_root
  end

  root 'landing#index'
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :memberships
  has_many :events
  has_many :users, through: :memberships

  validates :name, :description, :region, presence: true
  validates :description, length: { maximum: 130 }

  def admin?(user)
    memberships.admin.exists?(user_id: user.id)
  end

  def member?(user)
    memberships.normal.exists?(user_id: user.id)
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :find_group, only: [:show, :edit, :update, :destroy]

  def index
    @groups = Group.all
  end

  def show
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)

    AddMembershipToGroupService.perform(current_user, @group)

    if @group.save
      redirect_to root_path
    else
      flash[:errors] = @group.errors.full_messages
      render :new
    end
  end

  def edit
    authorize @group
  end

  def update
    authorize @group

    if @group.update(group_params)
      redirect_to group_path(@group)
    else
      flash[:errors] = @group.errors.full_messages
      render :edit
    end
  end

  def destroy
    authorize @group

    if @group.destroy
      redirect_to root_path
    else
      flash[:errors] = @group.errors.full_messages
      render :show
    end
  end

  private
  def find_group
    @group = Group.find(params[:id])
  end

  def group_params
    params.require(:group).permit(:name, :description, :region, :profile_picture_url, :cover_picture_url)
  end
end

app/views/groups/_form.html.erb
<%= form_for :group, url: url, method: method, data: { test: "#{type}_group_form" } do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :region %>
  <%= f.text_field :region %>

  <%= f.label :profile_picture_url %>
  <%= f.url_field :profile_picture_url %>

  <%= f.label :cover_picture_url %>
  <%= f.url_field :cover_picture_url %>

  <%= f.submit %>
<% end %>

app/views/groups/edit.html.erb
<section>
  <%= render 'form', url: group_path(@group), method: :put, type: 'update' %>

  <%= link_to 'Back', @group %>
</section>

app/views/groups/index.html.erb
<section data-test="groups_list">
  <% @groups.each do |group| %>
      <%= link_to group.name, group %>
      <p> Description: <%= group.description %> </p>
      <p> Region: <%= group.region %> </p>
  <% end %>

  <% unless @groups.exists? %>
    <p> No meetups were created yet, maybe you can create the first? </p>
  <% end %>

  <%= link_to 'Go back', root_path %>
</section>

app/views/groups/new.html.erb
<section>
  <%= render 'form', url: groups_path, method: :post, type: 'create' %>

  <%= link_to 'Go back', root_path %>
</section>

app/views/groups/show.html.erb
<section data-test="group_show">
  <h1> Name: <%= @group.name %> </h1>

  <p> Description: <%= @group.description %> </p>

  <p> Region: <%= @group.region %> </p>

  <% if current_user %>
    <% if policy(@group).update? %>
      <%= link_to 'Edit', edit_group_path(@group) %>
    <% end %>

    <% if policy(@group).destroy? %>
      <%= link_to_delete 'Delete', group_path(@group), :group %>
    <% end %>

    <% if policy(@group).leave? %>
      <%= link_to_delete 'Leave group', group_leave_path(@group), :membership %>
    <% end %>

    <% if policy(@group).create_an_event? %>
      <%= link_to 'Create event', new_group_event_path(@group) %>
    <% end %>

    <% if policy(@group).join? %>
      <%= link_to_create 'Join group', group_join_path(@group), :membership %>
    <% end %>
  <% end %>

  <%= link_to 'Events', group_events_path(@group) %>

  <%= link_to 'Go back', groups_path %>
</section>