config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' },
  path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }

  as :user do
    get 'login', to: 'devise/sessions#new'
  end

  resources :groups do
    post 'join', to: 'memberships#create'
    delete 'leave', to: 'memberships#destroy'

    get 'members', to: 'members#index'

    resources :events do
      resources 'organizers', only: [:create, :destroy]

      post 'rsvp', to: 'rsvps#create'
    end
  end

  authenticated :user do
    root 'dashboard#index', as: :authenticated_root
  end

  root 'landing#index'
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :group
  has_many :event_organizers, inverse_of: :organized_event
  has_many :organizers, through: :event_organizers
  has_many :event_rsvps
  has_many :rsvps, through: :event_rsvps

  validates :name, :description, :address, :start_date, :end_date, presence: true

  def full?
    rsvps_limit <= event_rsvps.where(answer: true).count
  end

  def organizer?(user)
    organizers.exists?(user.id)
  end

  def rsvp_answer(user)
    event_rsvps.where(user_id: user.id).first&.answer
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :find_group, only: [:index, :show, :new, :create, :edit, :update, :destroy]
  before_action :find_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = @group.events
  end

  def show
  end

  def new
    @event = Event.new(group_id: @group.id)

    authorize @event
  end

  def create
    @event = Event.new(event_params)
    @event.group = @group
    @event.organizers << current_user

    authorize @event

    if @event.save
      redirect_to group_event_path(@group, @event)
    else
      flash[:errors] = @event.errors.full_messages
      render :new
    end
  end

  def edit
    authorize @event
  end

  def update
    authorize @event

    if @event.update(event_params)
      redirect_to group_event_path(@group, @event)
    else
      flash[:errors] = @event.errors.full_messages
      render :edit
    end
  end

  def destroy
    authorize @event

    if @event.destroy
      redirect_to group_path(@group)
    else
      flash[:errors] = @event.errors.full_messages
      render :show
    end
  end

  private

  def find_group
    @group = Group.find_by!(id: params[:group_id])
  end

  def find_event
    @event = @group.events.find_by!(id: params[:id])
  end

  def event_params
    params.require(:event).permit(:name, :description, :address, :start_date, :end_date, :cover_picture_url)
  end
end

app/views/events/_form.html.erb
<%= form_for :event, url: url, method: method, data: { test: "#{type}_event_form" } do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :address %>
  <%= f.text_field :address %>

  <%= f.label :rsvps_limit %>
  <%= f.number_field :rsvps_limit, min: 1 %>

  <%= f.date_select :start_date %>
  <%= f.time_select :start_date, ignore_date: true %>

  <%= f.date_select :end_date %>
  <%= f.time_select :end_date, ignore_date: true %>

  <%= f.label :cover_picture_url %>
  <%= f.url_field :cover_picture_url %>

  <%= f.submit %>
<% end %>

app/views/events/edit.html.erb
<section>
  <%= render 'form', url: group_event_path(@group, @event), method: :put, type: 'update' %>
  <%= link_to 'Go back', group_event_path(@group, @event) %>
</section>

app/views/events/index.html.erb
<% @events.each do |event| %>
  <%= link_to event.name, group_event_path(@group, event) %>
  <p> Description: <%= event.description %> </p>
  <p> Address: <%= event.address %> </p>
  <p> Start Date: <%= event.start_date %> </p>
  <p> End Date: <%= event.end_date %> </p>
<% end %>

<% unless @events.exists? %>
  <p> No events yet! </p>
<% end %>

<%= link_to 'Create event', new_group_event_path(@group) %>

<%= link_to 'Go back', @group %>

app/views/events/new.html.erb
<section>
  <%= render 'form', url: group_events_path(@group), method: :post, type: 'create' %>
  <%= link_to 'Go back', @group %>
</section>

app/views/events/show.html.erb
<h1> Name: <%= @event.name %> </h1>

<p> Description: <%= @event.description %> </p>

<p> Address: <%= @event.address %> </p>

<p> Start Date: <%= @event.start_date %> </p>

<p> End Date: <%= @event.end_date %> </p>

<h2> Organizers </h2>

<% @event.organizers.each do |organizer| %>
  <%= organizer.name %>
<% end %>

<% @event.rsvps.any? do %>
  <p>RSVPS</p>

  <% @event.event_rsvps.each do |event_rsvp| %>
    <%= event_rsvp.rsvp_name %>

    <%= event_rsvp.answer %>
  <% end %>
<% end %>

<% if current_user %>
  <% if policy(@event).update? %>
    <%= link_to 'Edit', edit_group_event_path(@group, @event) %>
  <% end %>

  <% if policy(@event).destroy? %>
    <%= link_to_delete 'Delete', group_event_path(@group, @event), :event %>
  <% end %>

  <% if policy(@event).rsvp_with_yes? %>
    <p>RSVP</p>

    <%= link_to_create 'yes', group_event_rsvp_path(@group, @event), :rsvp %>
  <% end %>

  <% if policy(@event).rsvp_with_no? %>
    <p>RSVP</p>

    <%= link_to_create 'no', group_event_rsvp_path(@group, @event), :rsvp %>
  <% end %>
<% end %>

<%= link_to 'Go back', group_events_path(@group) %>